import React from "react";
import { Svg } from "../../lib/styles";

type IDecentralizedProps = {
  color?: string;
};

export default function Decentralized({
  color = "#8261EE",
}: IDecentralizedProps) {
  return (
    <Svg width={50} height={50} fill="none" viewBox="0 0 50 50">
      <g transform="matrix(2,0,0,2,0,0)">
        <circle
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="#ffffff"
          cx="22"
          cy="8"
          r="1.5"
        ></circle>
        <circle
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="#ffffff"
          cx="11"
          cy="5"
          r="1"
        ></circle>
        <circle
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="#ffffff"
          cx="20"
          cy="15.5"
          r="1"
        ></circle>
        <circle
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="#ffffff"
          cx="1.5"
          cy="16.5"
          r="1"
        ></circle>
        <circle
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="#ffffff"
          cx="8.5"
          cy="13"
          r="1"
        ></circle>
        <circle
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="#ffffff"
          cx="11.5"
          cy="19.5"
          r="1.5"
        ></circle>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          x1="11"
          y1="6"
          x2="11.626"
          y2="18.008"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="9.487"
          y1="12.969"
          x2="20.561"
          y2="8.417"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="2.312"
          y1="15.918"
          x2="7.769"
          y2="13.676"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="12"
          y1="5"
          x2="20.561"
          y2="7.812"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="21.729"
          y1="9.5"
          x2="20.59"
          y2="14.695"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="10.139"
          y1="5.643"
          x2="1.762"
          y2="15.48"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="2.383"
          y1="16.964"
          x2="10.105"
          y2="18.945"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="13"
          y1="18.945"
          x2="19.235"
          y2="16.139"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="11.803"
          y1="5.591"
          x2="19.235"
          y2="14.861"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="10.566"
          y1="5.918"
          x2="8.943"
          y2="12.105"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="8.951"
          y1="13.888"
          x2="10.921"
          y2="18.115"
        ></line>
        <line
          stroke="#fff"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={color}
          x1="12.486"
          y1="18.372"
          x2="20.961"
          y2="9.082"
        ></line>
      </g>
    </Svg>
  );
}
